# Generated by Django 6.0.5 on 2026-05-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='continu',
            new_name='contenu',
        ),
    ]
